name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - name: Check PHP version
      run: php -v
    - name: Validate composer.json
      run: composer validate
    - name: Run the tests
      run: php vendor/bin/grumphp run --no-interaction
